[deps]
FinancialToolbox = "2edd74a5-e968-5e45-af77-76d29aa6a478"
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
NodeJS = "2bd173c7-0d6d-553b-b6af-13a54713934c"
PkgPage = "e7214860-93a8-4f22-b43d-bd447d1a2094"

[compat]
DataFrames = "1"
Franklin = "0.10"
PkgPage = "0.4"
NodeJS = "1, 2"
